# Generated by Django 4.0 on 2021-12-26 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Progress_bar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all', models.IntegerField(default=0, max_length=100, verbose_name='Всего')),
                ('current', models.IntegerField(default=0, max_length=100, verbose_name='На данный момент')),
            ],
        ),
    ]
