# Generated by Django 4.0 on 2021-12-26 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress_bar',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Статус'),
        ),
    ]
